name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install brane CLI
        uses: romnn/setup-brane-action@master

      - name: Build the brane package
        run: |
          sudo $HOME/.local/bin/brane build container.yml
          sudo $HOME/.local/bin/brane list
      - name: Import preprocessing package
        shell: bash
        run: |
          (set -o pipefail && echo "import data_processing;" | sudo $HOME/.local/bin/brane repl -c)
